version: '2'
services:

  mysql:
    container_name: mysql
    image: mysql:5.7.23
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  parser-service:
    container_name: parser-service
    build: ./parser-service
    ports:
    - "8080:8080"
    depends_on:
    - "mysql"